# Generated by Django 2.2.3 on 2020-03-24 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.IntegerField(db_column='AreaId', primary_key=True, serialize=False)),
                ('areaname', models.CharField(db_column='AreaName', max_length=45)),
            ],
            options={
                'db_table': 'area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.IntegerField(db_column='BranchId', primary_key=True, serialize=False)),
                ('branchaddress', models.TextField(db_column='BranchAddress')),
                ('mobileno', models.DecimalField(db_column='MobileNo', decimal_places=0, max_digits=10)),
            ],
            options={
                'db_table': 'branch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(db_column='CategoryId', primary_key=True, serialize=False)),
                ('categoryname', models.CharField(db_column='CategoryName', max_length=45, unique=True, verbose_name='Category ')),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.IntegerField(db_column='CityId', primary_key=True, serialize=False)),
                ('cityname', models.CharField(db_column='CityName', max_length=45)),
            ],
            options={
                'db_table': 'city',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('companyid', models.IntegerField(db_column='CompanyId', primary_key=True, serialize=False)),
                ('companyname', models.CharField(db_column='CompanyName', max_length=90)),
                ('logopath', models.TextField(db_column='logoPath')),
            ],
            options={
                'db_table': 'company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.IntegerField(db_column='CountryId', primary_key=True, serialize=False)),
                ('countryname', models.CharField(db_column='CountryName', max_length=45, unique=True)),
            ],
            options={
                'db_table': 'country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Coupondetail',
            fields=[
                ('id', models.AutoField(db_column='CouponId', primary_key=True, serialize=False)),
                ('couponcode', models.CharField(db_column='CouponCode', max_length=45, unique=True)),
                ('coupondescription', models.TextField(blank=True, db_column='CouponDescription', null=True)),
                ('coupondiscount', models.FloatField(db_column='CouponDiscount')),
                ('couponstartdate', models.DateField(db_column='CouponStartDate')),
                ('couponenddate', models.DateField(db_column='CouponEndDate')),
                ('mincartvalue', models.IntegerField(blank=True, db_column='MinCartValue', null=True)),
            ],
            options={
                'db_table': 'coupondetail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(db_column='OrderId', primary_key=True, serialize=False)),
                ('orderdatetime', models.DateTimeField(db_column='OrderDateTime')),
                ('emipayment', models.IntegerField(db_column='EmiPayment')),
                ('emimonths', models.IntegerField(blank=True, db_column='EmiMonths', null=True)),
                ('discountamount', models.IntegerField(blank=True, db_column='DiscountAmount', null=True)),
                ('gst_amount', models.IntegerField(db_column='GST_Amount')),
            ],
            options={
                'db_table': 'order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orderpayment',
            fields=[
                ('id', models.CharField(db_column='PaymentRefId', max_length=45, primary_key=True, serialize=False)),
                ('paymentdatetime', models.DateTimeField(db_column='PaymentDateTime')),
                ('amount', models.IntegerField(db_column='Amount')),
            ],
            options={
                'db_table': 'orderpayment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sellerdoclist',
            fields=[
                ('docid', models.IntegerField(db_column='DocId', primary_key=True, serialize=False)),
                ('docname', models.CharField(db_column='DocName', max_length=45, unique=True)),
            ],
            options={
                'db_table': 'sellerdoclist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.IntegerField(db_column='StateId', primary_key=True, serialize=False)),
                ('statename', models.CharField(db_column='StateName', max_length=45)),
            ],
            options={
                'db_table': 'state',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.IntegerField(db_column='SubCatId', primary_key=True, serialize=False)),
                ('subcatname', models.CharField(db_column='SubCatName', max_length=45, unique=True)),
                ('commission', models.FloatField(db_column='Commission')),
            ],
            options={
                'db_table': 'subcategory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254, unique=True)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
                ('addressline1', models.TextField(db_column='addressLine1')),
                ('mobileno', models.DecimalField(db_column='MobileNo', decimal_places=0, max_digits=10)),
                ('secque', models.TextField(db_column='secQue')),
                ('secqans', models.TextField(db_column='secQAns')),
                ('islocked', models.IntegerField(db_column='isLocked')),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userrole',
            fields=[
                ('roleid', models.IntegerField(db_column='RoleId', primary_key=True, serialize=False)),
                ('rolename', models.CharField(db_column='RoleName', max_length=45, unique=True)),
            ],
            options={
                'db_table': 'userrole',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('advid', models.AutoField(db_column='AdvId', primary_key=True, serialize=False)),
                ('advregno', models.CharField(blank=True, db_column='AdvRegNo', max_length=45, null=True, unique=True, verbose_name='Registration No')),
                ('height', models.IntegerField(db_column='Height')),
                ('width', models.IntegerField(db_column='Width')),
                ('minquantity', models.IntegerField(blank=True, db_column='MinQuantity', null=True, verbose_name='Minimum quantity')),
                ('addressline1', models.TextField(db_column='AddressLine1', verbose_name='Address')),
                ('stock', models.IntegerField(blank=True, db_column='Stock', null=True)),
                ('defaultimgpath', models.FileField(blank=True, db_column='DefaultImgPath', null=True, upload_to='')),
                ('area_areaid', models.ForeignKey(blank=True, db_column='Area_AreaId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='admm.Area')),
                ('auth_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='admm.User')),
                ('city_cityid', models.ForeignKey(blank=True, db_column='City_CityId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='admm.City')),
                ('subcategory_subcatid', models.ForeignKey(db_column='SubCategory_SubCatId', on_delete=django.db.models.deletion.DO_NOTHING, to='admm.Subcategory')),
            ],
            options={
                'db_table': 'advertisement',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Offerdetail',
            fields=[
                ('id', models.AutoField(db_column='OfferId', primary_key=True, serialize=False)),
                ('description', models.TextField(db_column='Description', default=None)),
                ('discount', models.FloatField(db_column='Discount')),
                ('startdate', models.DateField(db_column='OfferStartDateTime')),
                ('enddate', models.DateField(db_column='OfferEndDateTime')),
            ],
            options={
                'db_table': 'offerdetail',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.IntegerField(db_column='PackageId', primary_key=True, serialize=False)),
                ('description', models.TextField(db_column='PackageDescription', default=None, max_length=70)),
                ('discount', models.FloatField(db_column='Discount', default=None)),
                ('startdate', models.DateField(db_column='StartDate')),
                ('enddate', models.DateField(db_column='EndDate')),
            ],
            options={
                'db_table': 'package',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Advimgs',
            fields=[
                ('id', models.ForeignKey(db_column='Advertisement_AdvId', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='admm.Advertisement')),
                ('adv_img', models.FileField(db_column='ImagePath', upload_to='')),
            ],
            options={
                'db_table': 'advimgs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cartdetail',
            fields=[
                ('id', models.ForeignKey(db_column='Advertisement_AdvId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='admm.Advertisement')),
                ('price', models.IntegerField(db_column='Price')),
                ('startdate', models.DateField(blank=True, db_column='StartDate', null=True)),
                ('enddate', models.DateField(blank=True, db_column='EndDate', null=True)),
                ('quantity', models.IntegerField(blank=True, db_column='Quantity', null=True)),
            ],
            options={
                'db_table': 'cartdetail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Commissiondetail',
            fields=[
                ('id', models.ForeignKey(db_column='Advertisement_AdvId', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='admm.Advertisement')),
                ('commission', models.FloatField(db_column='Commission')),
                ('createddatetime', models.DateTimeField(db_column='CreatedDateTime')),
            ],
            options={
                'db_table': 'commissiondetail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Durationwisepricing',
            fields=[
                ('advertisement_advid', models.ForeignKey(db_column='Advertisement_AdvId', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='admm.Advertisement')),
                ('noofdays', models.IntegerField(db_column='NoOfDays')),
                ('price', models.IntegerField(db_column='Price')),
            ],
            options={
                'db_table': 'durationwisepricing',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Offercoveringadvs',
            fields=[
                ('id', models.ForeignKey(db_column='OfferDetail_OfferId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='admm.Offerdetail')),
            ],
            options={
                'db_table': 'offercoveringadvs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orderdetails',
            fields=[
                ('id', models.ForeignKey(db_column='Order_OrderId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='admm.Order')),
                ('advprice', models.IntegerField(db_column='AdvPrice')),
                ('advstartdate', models.DateField(db_column='AdvStartDate')),
                ('advenddate', models.DateField(db_column='AdvEndDate')),
                ('quantity', models.IntegerField(blank=True, db_column='Quantity', null=True)),
                ('cancellationdatetime', models.DateTimeField(blank=True, db_column='CancellationDateTime', null=True)),
                ('reasonofcancellation', models.TextField(blank=True, db_column='ReasonOfCancellation', null=True)),
                ('paymentrefid', models.CharField(blank=True, db_column='PaymentRefId', max_length=70, null=True, unique=True)),
                ('paymentdatetime', models.DateTimeField(blank=True, db_column='PaymentDateTime', null=True)),
                ('refundedamount', models.IntegerField(blank=True, db_column='RefundedAmount', null=True)),
                ('served', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orderdetails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wishlistdetail',
            fields=[
                ('id', models.ForeignKey(db_column='Advertisement_AdvId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='admm.Advertisement')),
            ],
            options={
                'db_table': 'wishlistdetail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Updationinorder',
            fields=[
                ('id', models.ForeignKey(db_column='OrderId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='ordIdForUpd', serialize=False, to='admm.Orderdetails')),
                ('updationdatetime', models.DateTimeField(db_column='UpdationDateTime')),
                ('amount', models.IntegerField(blank=True, db_column='Amount', null=True)),
                ('paymentrefid', models.CharField(blank=True, db_column='PaymentRefId', max_length=45, null=True)),
                ('paymentdatetime', models.DateTimeField(blank=True, db_column='PaymentDateTime', null=True)),
            ],
            options={
                'db_table': 'updationinorder',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sellerdocdetail',
            fields=[
                ('auth_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='admm.User')),
                ('docpath', models.TextField(db_column='DocPath')),
                ('sellerdoclist_docid', models.ForeignKey(db_column='sellerdoclist_DocId', on_delete=django.db.models.deletion.DO_NOTHING, to='admm.Sellerdoclist')),
            ],
            options={
                'db_table': 'sellerdocdetail',
                'managed': True,
                'unique_together': {('auth_user', 'sellerdoclist_docid')},
            },
        ),
        migrations.CreateModel(
            name='PackageHasAdv',
            fields=[
                ('id', models.ForeignKey(db_column='Package_PackageId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='admm.Package')),
                ('quantity', models.IntegerField(blank=True, db_column='Quantity', null=True)),
                ('advertisement_advid', models.ForeignKey(db_column='Advertisement_AdvId', on_delete=django.db.models.deletion.DO_NOTHING, to='admm.Advertisement')),
            ],
            options={
                'db_table': 'package_has_adv',
                'managed': True,
                'unique_together': {('id', 'advertisement_advid')},
            },
        ),
        migrations.CreateModel(
            name='Orderfeedback',
            fields=[
                ('odrid', models.ForeignKey(db_column='orderdetails_Order_OrderId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='orderfeedback', serialize=False, to='admm.Orderdetails')),
                ('datetime', models.DateTimeField(db_column='FeedbackDateTime')),
                ('description', models.TextField(blank=True, db_column='FeedbackText', null=True)),
                ('rating', models.IntegerField(db_column='Rating')),
                ('responsedatetime', models.DateTimeField(blank=True, db_column='ResponseDateTime', null=True)),
                ('responsetext', models.TextField(blank=True, db_column='ResponseText', null=True)),
                ('advid', models.ForeignKey(db_column='orderdetails_Advertisement_AdvId', on_delete=django.db.models.deletion.DO_NOTHING, related_name='advIdOrderFeedback', to='admm.Orderdetails')),
                ('auth_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='admm.User')),
            ],
            options={
                'db_table': 'orderfeedback',
                'managed': True,
                'unique_together': {('odrid', 'advid')},
            },
        ),
        migrations.CreateModel(
            name='Complaintdetail',
            fields=[
                ('orderdetails_order_orderid', models.ForeignKey(db_column='orderdetails_Order_OrderId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='complaintOrder', serialize=False, to='admm.Orderdetails')),
                ('datetime', models.DateTimeField(db_column='ComplaintDateTime')),
                ('description', models.TextField(db_column='ComplaintDescription')),
                ('responsetext', models.TextField(blank=True, db_column='ResponseText', null=True)),
                ('responsedatetime', models.DateTimeField(blank=True, db_column='ResponseDateTime', null=True)),
                ('auth_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='admm.User')),
                ('orderdetails_advertisement_advid', models.ForeignKey(db_column='orderdetails_Advertisement_AdvId', on_delete=django.db.models.deletion.DO_NOTHING, related_name='advIdComplaint', to='admm.Orderdetails')),
            ],
            options={
                'db_table': 'complaintdetail',
                'managed': True,
                'unique_together': {('orderdetails_order_orderid', 'orderdetails_advertisement_advid', 'datetime')},
            },
        ),
    ]
