# Generated by Django 2.2.3 on 2020-03-29 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfeedback',
            name='odrid',
            field=models.ForeignKey(db_column='orderdetails_Order_OrderId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='orderfeedback', serialize=False, to='admm.Order'),
        ),
    ]
