# Generated by Django 3.0.5 on 2020-09-03 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admm', '0003_auto_20200329_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.TextField(db_column='PackageDescription', default=None),
        ),
        migrations.AlterField(
            model_name='packagehasadv',
            name='advertisement_advid',
            field=models.ForeignKey(db_column='Advertisement_AdvId', on_delete=django.db.models.deletion.CASCADE, to='admm.Advertisement'),
        ),
        migrations.AlterField(
            model_name='packagehasadv',
            name='id',
            field=models.ForeignKey(db_column='Package_PackageId', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='admm.Package'),
        ),
    ]
