# Generated by Django 3.0.5 on 2020-09-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admm', '0004_auto_20200903_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.TextField(db_column='PackageDescription', default=None, max_length=200),
        ),
    ]
