# Generated by Django 2.2.3 on 2019-12-20 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admm', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Docdetail',
        ),
    ]
