# Generated by Django 2.2.3 on 2019-12-26 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admm', '0002_delete_docdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userdetail',
        ),
    ]
